services:
  - type: web
    name: gujarati-snacks-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    rootDirectory: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_ATLAS_URI
        sync: false
      - key: MONGODB_OPTIONS
        value: '{"useNewUrlParser": true, "useUnifiedTopology": true, "retryWrites": true, "w": "majority"}'
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLIENT_URL
        value: https://gujarati-snacks.vercel.app
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: EMAILJS_PUBLIC_KEY
        value: PetqFRmfT0ag19QmD
      - key: EMAILJS_TEMPLATE_ID
        value: template_tr8ak6u
      - key: EMAILJS_SERVICE_ID
        value: service_rp0782i
      - key: ADMIN_EMAIL
        value: dhairyarup@gmail.com 